/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"


#ifndef _Included_com_example_facedetector_Humandetector
#define _Included_com_example_facedetector_Humandetector
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_facedetector_Humandetector_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_facedetector_Humandetector_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_facedetector_Humandetector
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_facedetector_Humandetector_loadCascade
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_facedetector_Humandetector
 * Method:    detect
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_facedetector_Humandetector_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
